---@class IslandNewbieGuideTips01_UIBP_C:UNewbieGuideWidget
---@field OnCreateAndShow:fun(GuideId:int32,UIConfigIndex:int32)
---@field DX_Loop UWidgetAnimation
---@field UTRichTextBlock_OperatingTips1 UUTRichTextBlock
