---@class LeftQueueInfo_Item_UIBP_C:ULeftQueueItemWidget
---@field GetConfigLeft:fun():bool
---@field GetLuaModule:fun():FString
---@field RefreshTranslationY:fun()
---@field InitLeftQueueItemData:fun(observerMode:bool,ImageDownLoader:UImageDownloader,QueueControl:LeftQueueInfoControl_UIBP_C,_platformIcons:ULuaMapHelper)
---@field ExecuteObserverModeStatusInBlueprint:fun()
---@field Construct:fun()
---@field SetQueueItemData:fun(RecordData:FClientFatalDamageRecordData)
---@field ExecuteStatusInBlueprint:fun()
---@field GlobalObserverSwitchingAnimation UWidgetAnimation
---@field GlobalObserverInitAnimation UWidgetAnimation
---@field SwitchingAnimation UWidgetAnimation
---@field NormalAnimation UWidgetAnimation
---@field Border_ColorSet UBorder
---@field CanvasPanel_6 UCanvasPanel
---@field ItemContainer UGridPanel
---@field KillInfo_BGSlot_UIBP KillInfo_BGSlot_UIBP_C
---@field KillInfo_Prompt_UIBP KillInfo_Prompt_UIBP_C
---@field WidgetSwitcher_Type UWidgetSwitcher
---@field TransformOffsetY float
---@field ParentQueue LeftQueueInfoControl_UIBP_C
---@field config int32
