---@class BP_TestLuaKeyMapping_C:AActor
---@field GetLuaModule:fun():FString
---@field UserConstructionScript:fun()
---@field ReceiveTick:fun(DeltaSeconds:float)
---@field StaticMesh UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
