---@class HAS_Skill_Hide_FireR_UIBP_C:UUTSkillIconWidgetTemplate
---@field GetCurrentCDPercentage:fun(InCurEnergy:float,InMaxEnergy:float,DeltaEnergy:float):bool,float
---@field Construct:fun()
---@field RemoveSkillUI:fun()
---@field DX_UpgradeSkills UWidgetAnimation
---@field DX_UpgradeSkills_old UWidgetAnimation
---@field DX_RefreshSkill UWidgetAnimation
---@field Border_SkillSlot UBorder
---@field Button_0 UButton
---@field CanvasPanel_Lock UCanvasPanel
---@field CanvasPanel_tips UCanvasPanel
---@field Custom_Canvas_17 CustomizeCanvasPanel_BP_C
---@field Image_CDTime UImage
---@field Image_Icon UImage
---@field Text_Time UTextBlock
---@field FunctionBPParam ULuaMapHelper
---@field ReplaceWidgetName FString
---@field ReplaceWidgetOuter FString
---@field BeReplaceWidgetVisible ESlateVisibility
