---@class BP_BattleRoyaleGameModeTeamPUBG_Four_MidAutumn009_C:ABP_BattleRoyaleGameModeTeamPUBG_C
---@field UserConstructionScript:fun()
---@field AIGroupManager UAIGroupManagerComponent
---@field AIWorldSoundManager UAIWorldSoundManagerComponent
---@field AnimalTeleport UAnimalTeleportComponent
---@field SpawnMonsterHelperComp USpawnMonsterHelperComp
