---@class BP_BattleRoyaleGameMode_chicken_C:ABP_BattleRoyaleGameMode_C
---@field UserConstructionScript:fun()
---@field BP_AIWorldSoundManager BP_AIWorldSoundManager_C
---@field AIGroupManager UAIGroupManagerComponent
---@field AnimalTeleport UAnimalTeleportComponent
---@field SpawnMonsterHelperComp USpawnMonsterHelperComp
