---@class FAnswerInfo
---@field GiveLikeTeammateArray ULuaArrayHelper
---@field GiveLikeOBArray ULuaArrayHelper
---@field OperationID int32
---@field CurrentTime int32
---@field PlayerKey FString
---@field GiveLikeType int32
