---@class MoveBlendAnimBP_InfectedMan_03_C:USubAnimInstance_Event
---@field BlueprintInitializeAnimation:fun()
---@field ParentExtraAnimInstanceBase USTExtraAnimInstanceBase
---@field ParentOwnerBaseCharacter ASTExtraBaseCharacter
---@field MoveStateInitFM FSTExtraAnimFM_MoveState
