---@class sports_guide_UIBP_C:UUAEUserWidget
---@field HideTmodeTipsUI:fun()
---@field ShowTmodeTipsUI:fun()
---@field ReceivedInitWidget:fun()
---@field Button_jingjiclose UButton
---@field IsShow bool
