---@class AsianGames_FlagItem_UIBP_C:UMapUIMarkBaseWidget
---@field refresh:fun(State:int32)
---@field UpdateUIBPState:fun(InState:FCustomMarkEventData)
---@field OnUIBPShow:fun(InState:FCustomMarkEventData)
---@field CanvasPanel_Done UCanvasPanel
---@field CanvasPanel_Select UCanvasPanel
---@field Image_Icon UImage
---@field NewButton_Click UNewButton
