---@class AsianOB_TipsChampion_UIBP_C:UUAEUserWidget
---@field Construct:fun()
---@field Button_Determine UNewButton
---@field Image_Flag UImage
---@field TextBlock_CountryName UTextBlock
---@field TextBlock_Ranking UTextBlock
