---@class Ingame_YearbeastTips02_UIBP_C:UNewbieGuideWidget
---@field OnCreateAndShow:fun(GuideId:int32,UIConfigIndex:int32)
---@field DX_Loop UWidgetAnimation
---@field UTRichTextBlock_YearBeastTips02 UUTRichTextBlock
