---@class BP_FortressZombieGroupSpot9_C:AUAEHouseActor
---@field UserConstructionScript:fun()
---@field BP_ItemSpotComponent BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
