---@class BP_FortressZombieCarGroupSpotA_C:AUAEHouseActor
---@field UserConstructionScript:fun()
---@field BP_ItemSpotComponent1 BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
