---@class ReplayCompleteInterface_C:UInterface
---@field InitDeathBoxWidget:fun(RelationshipWithTarget:ERelationshipWithTarget)
---@field SetPlayerMarkIcon:fun(RelationShipWithTarget:ERelationshipWithTarget,MoveState:EPlayerMoveState)
