---@class BP_Sniper_Win94_C:BP_ShootWeaponBase_C
---@field UserConstructionScript:fun()
---@field WeaponAnimList_Sniper_Win94 WeaponAnimList_Sniper_Win94_C
---@field WeaponPostReloadState UWeaponPostReloadState
---@field WeaponPostFireState UWeaponPostFireState
---@field WeaponPreFireState UWeaponPreFireState
---@field bUseIdleAnim_0_0 bool
