---@class BP_Skill_HIder_TransToTarget_C:AUAESkill
---@field TransToTarget:fun()
---@field UserConstructionScript:fun()
---@field UTSkillEventEffectMapForEditor1 UUTSkillEventEffectMapForEditor
---@field UTSkillEventEffectMapForEditor UUTSkillEventEffectMapForEditor
---@field UTSkillSpecificAction UUTSkillSpecificAction
---@field UAESkillPhase UUAESkillPhase
---@field DefaultSceneRoot USceneComponent
