---@class BP_GameModeTeam_FourTherions_Four_C:ABP_BattleRoyaleGameModeTeamPUBG_C
---@field UserConstructionScript:fun()
---@field AIGroupManager UAIGroupManagerComponent
---@field AIWorldSoundManager UAIWorldSoundManagerComponent
---@field AnimalTeleport UAnimalTeleportComponent
---@field SpawnMonsterHelperComp USpawnMonsterHelperComp
