---@class BP_Sniper_Mini14_C:BP_ShootWeaponBase_C
---@field UserConstructionScript:fun()
---@field WeaponAnimList_Sniper_Mini14 WeaponAnimList_Sniper_Mini14_C
---@field Arrow1 UArrowComponent
---@field bUseIdleAnim_0_0 bool
