---@class BP_UGCNormalGrenade_Weapon_Template_C:AUGCProjectileWeapon
---@field UserConstructionScript:fun()
---@field BP_WeaponDynamicAnimListManager BP_WeaponDynamicAnimListManager_C
---@field BP_ThrowComponent BP_ThrowComponent_C
---@field ThrowableWeaponCrossHair UThrowableWeaponCrossHairComponent
---@field WeaponAnimList_Grenade WeaponAnimList_Grenade_C
---@field WeaponEntity UWeaponEntity
---@field WeaponSpecificHandler UWeaponSpecificHandler
---@field WeaponStateDefault UWeaponStateDefault
---@field WeaponStateManager UWeaponStateManager
