---@class Skill_EnterBunker_BP_2_C:AUAESkill
---@field UserConstructionScript:fun()
---@field UAESkillPhase1 UUAESkillPhase
---@field UAESkillPhase UUAESkillPhase
---@field DefaultSceneRoot USceneComponent
