---@class PickUpItem_S_BP_C:UUAEUserWidget
---@field CheckHasMarked:fun()
---@field OnDragDetected:fun(MyGeometry:FGeometry,PointerEvent:FPointerEvent):UDragDropOperation
---@field OnDragEnd:fun()
---@field OnDraging:fun(MousePos:FVector2D)
---@field OnDragBegin:fun()
---@field OnDoubleClick:fun()
---@field OnClick:fun()
---@field CheckArmoredDurableIsZeroStatus:fun()
---@field FindDualbility:fun(Array:ULuaArrayHelper):float
---@field RefreshElectricty:fun(AdditionalData:ULuaArrayHelper)
---@field RefreshIcon:fun(Icon:UObject)
---@field ShowDurable:fun()
---@field UpdateUseless:fun(useful:bool,marked:bool)
---@field GetUseless:fun():bool
---@field OnTouchGesture:fun(MyGeometry:FGeometry,GestureEvent:FPointerEvent):FEventReply
---@field HandlePickup:fun()
---@field OnTouchStarted:fun(MyGeometry:FGeometry,InTouchEvent:FPointerEvent):FEventReply
---@field OnTouchEnded:fun(MyGeometry:FGeometry,InTouchEvent:FPointerEvent):FEventReply
---@field UpdateItemData:fun(ItemData:FBattleSearchItemSortingInfo,Marked:bool)
---@field OnMouseLeave:fun(MouseEvent:FPointerEvent)
---@field CanvasPanel_ColdModeInfo UCanvasPanel
---@field EnergySocket UCustomSocketPanel
---@field Image_CanEquippedIconBG UImage
---@field Image_CanEquippedItemBG UImage
---@field Image_GiftBoxBG UImage
---@field Image_ItemBG UImage
---@field Image_ItemGiftBoxBG UImage
---@field Image_ItemIcon UImage
---@field Image_ItemIconBG UImage
---@field ItemContent11 UTextBlock
---@field ItemContent2 UUTRichTextBlock
---@field ProgressBar_Damage UProgressBar
---@field ProgressBar_Marking UProgressBar
---@field TextBlock_ItemNum UTextBlock
---@field WidgetSwitcher_Mark UWidgetSwitcher
---@field WidgetSwitcher_MarkBg UWidgetSwitcher
---@field ItemDataStructure FSearchedPickUpItemResult
---@field bHasStartedTouchIn bool
---@field bHasTipsShow bool
---@field ParentUserWidget UUserWidget
---@field useful bool
---@field pickCount int32
---@field LastItemID int32
---@field CurLastDurabilityRadio float
---@field PressTimeHandle FTimerHandle
---@field ClickTimeHandle FTimerHandle
---@field ClickTimeThreshold float
---@field DragThanClickOffsetTime float
---@field CurrentItemData FBattleSearchItemSortingInfo
---@field PressTimeHandle_Ani FTimerHandle
---@field PressTimeHandle_AniTime float
---@field hasMarked bool
---@field OperationDone bool
---@field IsTouchEnd bool
---@field PressDownIndex int32
---@field PressDownTime float
---@field PressDownPos FVector2D
---@field BeginDragThreshold float
