---@class ProfessionModeTopBG_UIBP_C:UUAEUserWidget
---@field SetResultTop:fun(single:bool):bool
---@field SetResultVictory:fun(vic:bool):bool
---@field ShowResultModeBGDetail:fun(show:bool):bool
---@field CanvasPanel_ProfessionModevictory1 UCanvasPanel
---@field CanvasPanel_ProfessionModevictory2 UCanvasPanel
---@field Image_ProfessionMode_TopBG1 UImage
---@field Image_ProfessionModeBG_TopBG2 UImage
---@field Image_ProfessionModevictoryBG1 UImage
---@field Image_ProfessionModevictoryBG2 UImage
---@field WidgetSwitcher_ProfessionModeTopBGType UWidgetSwitcher
