---@class UGC_M416_C:AActor
---@field UserConstructionScript:fun()
---@field StaticMesh UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
