---@class BattleItemHandle_Pistol_C:UBattleItemHandleWeaponBase_Handle_C
---@field GetOwingtWeapon:fun():ASTExtraWeapon
---@field LocalHandleDisuse:fun()
---@field GetAvailableTargetLogicSocketName:fun(TargetSocket:FName):FName,bool,bool
---@field GetAvailableInstantLogicSocketName:fun():FName,bool,bool
---@field CreateWrapperOnGround:fun()
---@field JudgeHasTargetAttachmentSlot:fun(TypeSpecificId:int32):bool
---@field HandlePickup:fun(ItemContainer:TScriptInterface,PickupInfo:FBattleItemPickupInfo,Reason:EBattleItemPickupReason):bool
---@field HandleUse:fun(Target:FBattleItemUseTarget,Reason:EBattleItemUseReason):bool
---@field HandleDrop:fun(InCount:int32,Reason:EBattleItemDropReason):bool
---@field HandleDisuse:fun(Reason:EBattleItemDisuseReason):bool
---@field Socket FName
---@field CharacterItemHandle UBattleItemHandleBase
---@field WeaponClass UClass
---@field TargetWeaponActor ASTExtraWeapon
---@field LogicSlotName FName
---@field WrapperClass UClass
---@field WeaponManager UWeaponManagerComponent
---@field AvailableWeaponAttachment ULuaArrayHelper
---@field WeaponAttachmentSockTypeList ULuaArrayHelper
