---@class BP_CheckTriggerArea_C:ABP_VehicleTriggerArea_C
---@field GetLuaModule:fun():FString
---@field UserConstructionScript:fun()
---@field ParticleSystemComponent UParticleSystemComponent
---@field StaticMeshComponent2 UStaticMeshComponent
