---@class BP_VehicleAreaTLog_C:AActor
---@field GetLuaModule:fun():FString
---@field UserConstructionScript:fun()
---@field ReceiveTick:fun(DeltaSeconds:float)
---@field DefaultSceneRoot USceneComponent
