---@class BP_Grenade_Smoke_Weapon_C:ASTExtraWeapon_Throw
---@field UserConstructionScript:fun()
---@field BP_Grenade_Smoke_Weapon_AnimList BP_Grenade_Smoke_Weapon_AnimList_C
---@field BP_WeaponDynamicAnimListManager BP_WeaponDynamicAnimListManager_C
---@field BP_ThrowComponent BP_ThrowComponent_C
---@field ThrowableWeaponCrossHair UThrowableWeaponCrossHairComponent
---@field WeaponAnimList_Grenade WeaponAnimList_Grenade_C
---@field WeaponEntity UWeaponEntity
---@field WeaponSpecificHandler UWeaponSpecificHandler
---@field WeaponStateDefault UWeaponStateDefault
---@field WeaponStateManager UWeaponStateManager
