---@class Black_BombingArea_UIBP_C:UMapUIMarkBaseWidget
---@field OnUIBPCreate:fun(InState:FCustomMarkEventData,ParentState:EMarkParentWidget,inRealLevelToMapScale:float,inMapScale:float)
---@field UpdateMarkSize:fun(inScale:float,inMapScale:float,MapScaleInUI:float)
---@field VisiableSize float
---@field bUpdateSize bool
