---@class HuntedTargetZone_UIBP_C:UMapUIMarkBaseWidget
---@field OnUIBPCreate:fun(InState:FCustomMarkEventData,ParentState:EMarkParentWidget,inRealLevelToMapScale:float,inMapScale:float)
---@field UpdateMarkSize:fun(inScale:float,inMapScale:float,MapScaleInUI:float)
---@field OnUIBPShow:fun(InState:FCustomMarkEventData)
---@field UpdateUIBPState:fun(InState:FCustomMarkEventData)
---@field SmoothShow UWidgetAnimation
---@field Image_AirAttackZoneIcon UImage
---@field AreaRadius float
