---@class MiniMapPlayerIconInterface_C:UInterface
---@field BindPlayerStateDelagate:fun(PlayerState:ASTExtraPlayerState):bool
---@field SwitchVisibility:fun(IsShow:bool):bool
---@field GetRotationDisplayWidget:fun():UWidget
---@field SetSelfStyle:fun(IsSelf:bool):bool
---@field SetTeammateInfo:fun(TeammateIndex:int32,TeammateColor:FLinearColor):bool
---@field UseSingleStyle:fun():bool
