---@class StarGame_HelicopterMark_UIBP_C:UMapUIMarkBaseWidget
---@field refresh:fun(State:int32)
---@field UpdateUIBPState:fun(InState:FCustomMarkEventData)
---@field OnUIBPShow:fun(InState:FCustomMarkEventData)
---@field Image_BonfireIcon UImage
