---@class BP_UGCMobilePlayerPlotControl_C:UPlayerPlotControlComponent
---@field GetPlotManager:fun():TScriptInterface
---@field SetCharacterMovementEnable:fun(bEnable:bool)
---@field PlotManagerRef BP_UGCMobilePlotManager_C
---@field CurMovmentEnable bool
