---@class ReliveModeTopBG_UIBP_C:UUAEUserWidget
---@field SetResultTop:fun(single:bool):bool
---@field SetResultVictory:fun(vic:bool):bool
---@field ShowResultModeBGDetail:fun(show:bool):bool
---@field CanvasPanel_ReliveModevictory1 UCanvasPanel
---@field CanvasPanel_ReliveModevictory2 UCanvasPanel
---@field WidgetSwitcher_ReliveModeTopBGType UWidgetSwitcher
