---@class BP_Sniper_MK20NEW_C:BP_ShootWeaponNewBase_C
---@field UserConstructionScript:fun()
---@field WeaponAnimList_Sniper_MK20 WeaponAnimList_Sniper_MK20_C
---@field Arrow1 UArrowComponent
---@field bUseIdleAnim_0_0 bool
