---@class Minder_Skill1_C:AUAEAISkill
---@field UserConstructionScript:fun()
---@field UAESkillPhase2 UUAESkillPhase
---@field UAESkillPhase1 UUAESkillPhase
---@field UAESkillPhase UUAESkillPhase
---@field DefaultSceneRoot USceneComponent
