---@class VehicleGuideTips01_UIBP_C:UNewbieGuideWidget
---@field OnCreateAndShow:fun(GuideId:int32,UIConfigIndex:int32)
---@field DX_Loop UWidgetAnimation
---@field UTRichTextBlock_VehicleGuideTips1 UUTRichTextBlock
