---@class BP_Pet_Jige_Lobby_Team_C:AActor
---@field UserConstructionScript:fun()
---@field SK_Pet_Kuizai USkeletalMeshComponent
---@field SK_Pet_Jiojio USkeletalMeshComponent
---@field SK_Pet_Daidai USkeletalMeshComponent
---@field DefaultSceneRoot USceneComponent
