---@class BP_UGC_MachineGun_Custom_C:BP_UGC_ShootWeaponBase_C
---@field UserConstructionScript:fun()
---@field WeaponAnimList_Rifle_PP19 WeaponAnimList_MachineGun_PP19_C
---@field bUseIdleAnim_0_0 bool
