---@class BP_ExplosionEffect_BalloonGrenade_InAir_C:ASTExtraExplosionEffect
---@field UserConstructionScript:fun()
---@field DefaultSceneRoot USceneComponent
---@field ExplosionEffects UExplosionEffectDataAsset
