---@class BP_ExtraCottageRoom_3_C:ABP_ExtraCottageRoomBase_C
---@field UserConstructionScript:fun()
---@field ChildActor1 UChildActorComponent
---@field ChildActor UChildActorComponent
---@field Doors USceneComponent
---@field BP_ItemSpotComponent8 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent7 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent6 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent5 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent4 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent3 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent2 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent1 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
