---@class BP_ExtraCottageRoom_2_C:ABP_ExtraCottageRoomBase_C
---@field UserConstructionScript:fun()
---@field ChildActor UChildActorComponent
---@field ChildActor1 UChildActorComponent
---@field Doors USceneComponent
---@field BP_ItemSpotComponent15 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent14 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent13 BP_ItemSpotComponent_C
---@field Out BP_ItemSpotGroupComponent_C
---@field BP_ItemSpotComponent12 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent11 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent10 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent9 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent8 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent7 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent6 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent5 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent4 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent3 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent2 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent1 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
