---@class BP_chijijie_C:AUAEHouseActor
---@field UserConstructionScript:fun()
---@field BP_SnowmanSpot BP_WerewolfBoxSpotComponent_C
---@field BP_SnowmanGroupSceneComponent BP_WerewolfBoxGroupSceneComponent_C
---@field Arrow UArrowComponent
---@field DefaultSceneRoot USceneComponent
