---@class SeasonTopGame_Stage_TeamGrade_UIBP_C:UUAEUserWidget
---@field UpdateTeamInfo:fun(TeamName:FString,TeamLogoID:FString):FString
---@field UpdateGradeInfo:fun(Rank:int32,KillNumber:int32):int32
---@field UpdatePlayerInfo:fun(PlayerName:FString,Gender:int32,Visible:bool,PlayerUID:FString):bool
---@field UpdateKillNumber:fun(KillNumber:int32)
---@field UpdateRank:fun(Rank:int32)
---@field TextKillNumber UTextBlock
---@field TextRank UTextBlock
