---@class BP_HW_Baltic_HS_Mesh_watertank_C:ASTExtraHouseActor
---@field UserConstructionScript:fun()
---@field BP_ItemSpotComponent BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
---@field Baltic_watertank_1 UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
