---@class BP_HW_Baltic_HS_woodencrate_C:ASTExtraHouseActor
---@field UserConstructionScript:fun()
---@field BP_ItemSpotComponent2 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent1 BP_ItemSpotComponent_C
---@field BP_ItemSpotComponent BP_ItemSpotComponent_C
---@field BP_ItemSpotGroupComponent BP_ItemSpotGroupComponent_C
---@field Baltic_woodencrate UStaticMeshComponent
---@field DefaultSceneRoot USceneComponent
