---@class BP_SecretRoom_Building001_01_C:ABP_SecretRoomBase_C
---@field UserConstructionScript:fun()
---@field StaticMesh2 UStaticMeshComponent
---@field SpotGroupLocScene USpotGroupLocSceneComponent
---@field SpotLocScene4 USpotLocSceneComponent
---@field SpotLocScene3 USpotLocSceneComponent
---@field SpotLocScene2 USpotLocSceneComponent
---@field SpotLocScene1 USpotLocSceneComponent
---@field StaticMesh1 UStaticMeshComponent
---@field BP_SteelDoor UChildActorComponent
---@field Scene USceneComponent
