---@class BP_SecretRoom_Building058_C:ABP_SecretRoomBase_C
---@field UserConstructionScript:fun()
---@field StaticMesh4 UStaticMeshComponent
---@field SpotLocScene3 USpotLocSceneComponent
---@field SpotLocScene2 USpotLocSceneComponent
---@field SpotLocScene1 USpotLocSceneComponent
---@field SpotLocScene USpotLocSceneComponent
---@field SpotGroupLocScene USpotGroupLocSceneComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field BP_SteelDoor UChildActorComponent
---@field Scene USceneComponent
