---@class BP_SecretRoom_Building003_01_C:ABP_SecretRoomBase_C
---@field UserConstructionScript:fun()
---@field StaticMesh3 UStaticMeshComponent
---@field SpotLocScene1 USpotLocSceneComponent
---@field SpotLocScene4 USpotLocSceneComponent
---@field SpotLocScene2 USpotLocSceneComponent
---@field SpotLocScene USpotLocSceneComponent
---@field SpotGroupLocScene USpotGroupLocSceneComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field BP_SteelDoor UChildActorComponent
---@field Scene USceneComponent
