---@class UGCBackpackShootWeaponHandle_BP_C:UGCBackpackShootWeaponHandle_C
---@field GetLuaModule:fun():FString
---@field GetAvailableWeaponAttachment:fun():ULuaArrayHelper
---@field SetDropedByPlayerLua:fun(IsDropedPlayer:bool)
---@field GetDropedByPlayerLua:fun():bool
---@field CanEquip:fun():bool
---@field IsMainLogicSlot:fun(SlotName:FName):bool
---@field CanSwapEquipSlot:fun(OldSlotName:FName,NewSlotName:FName):bool
---@field HandleSwap:fun(OldSlotName:FName,NewSlotName:FName)
---@field HandleEquip:fun():bool
---@field GetWeaponClass:fun():UClass
---@field WeightBiggerThen:fun(A:int32,B:int32):bool
---@field ReturnAdditionalBullets:fun(BulletNum:int32):int32
---@field CanEquipAttach:fun(BPID:int32,ItemID:int32):bool
---@field EquipPendant:fun(PendantID:int32)
---@field AutoEquipPendant:fun()
---@field CheckPendantCanAttach:fun(PendantHandle:UBackpackWeaponAttachHandle):bool
---@field GetOwingtWeapon:fun():ASTExtraWeapon
---@field AutoEquipAttachments:fun()
---@field ReturnBullets:fun(Count:int32)
---@field UpdateEquipedAttach:fun(WeapAttachSockType:EWeaponAttachmentSocketType,WeapAttachItemHandle:UBackpackWeaponAttachHandle,IsEquip:bool)
---@field LocalHandleDisuse:fun(Reason:EBattleItemDisuseReason)
---@field CreateWrapperOnGround:fun()
---@field JudgeHasTargetAttachmentSlot:fun(TypeSpecificId:int32,AttachType:EWeaponAttachmentSocketType,AttachHandle:UBackpackWeaponAttachHandle):bool,bool,bool
---@field HandleDisuse:fun(Reason:EBattleItemDisuseReason):bool
---@field HandleUse:fun(Target:FBattleItemUseTarget,Reason:EBattleItemUseReason):bool
---@field HandleDrop:fun(InCount:int32,Reason:EBattleItemDropReason):bool
---@field HandlePickup:fun(ItemContainer:TScriptInterface,PickupInfo:FBattleItemPickupInfo,Reason:EBattleItemPickupReason):bool
---@field LocalAutoEquipAttachments:fun()
---@field CopyWeaponProperties:fun(SourceHandle:UBackpackWeaponHandle)
---@field OnEquip:fun()
---@field OnUnEquip:fun()
---@field OnSwapEquipSlot:fun(OldSlotName:FName,NewSlotName:FName)
---@field WeaponManager UWeaponManagerComponent
---@field Socket FName
---@field CharacterItemHandle UBattleItemHandleBase
---@field WeaponClass UClass
---@field TargetWeaponActor ASTExtraWeapon
---@field MainLogicSlot1Name FName
---@field MainLogicSlot2Name FName
---@field WrapperClass UClass
---@field WeaponAttachmentSockTypeList ULuaMapHelper
---@field BulletWrapperClass UClass
---@field EquipedWeapAttachments ULuaMapHelper
---@field bResetInitBulletInBullet bool
---@field bIsPistol bool
---@field SubLogicSlotName FName
---@field IsAttachPendant bool
---@field SoftWrapperClass UClass
---@field AvailableWeaponAttachmentUGC ULuaArrayHelper
---@field FilterSelected bool
---@field WeaponRecorld UClass
---@field UGCWrapperClass UClass
---@field ExtraTargetAutoUse bool
