---@class WeaponSkillItemHandleBase_BP_C:UBackpackWeaponSkillHandle
---@field GetWeaponClass:fun():UClass
---@field SpawnWrapperOnGround:fun(WrapperClass:UClass,bUseRandomLoc:bool):APickUpWrapperActor
---@field HandleDisuse:fun(Reason:EBattleItemDisuseReason):bool
---@field HandleUse:fun(Target:FBattleItemUseTarget,Reason:EBattleItemUseReason):bool
---@field HandleDrop:fun(InCount:int32,Reason:EBattleItemDropReason):bool
---@field HandlePickup:fun(ItemContainer:TScriptInterface,PickupInfo:FBattleItemPickupInfo,Reason:EBattleItemPickupReason):bool
---@field ExtractItemData:fun():FBattleItemData
---@field SetClientItemContainer:fun(ItemContainer:TScriptInterface)
---@field OwningPlayerController ASTExtraPlayerController
---@field OwningCharacter ASTExtraBaseCharacter
---@field OwningBackpackComponent UBackpackComponent
---@field WrapperPutdownTrans FTransform
---@field SourceWrapperTrans FTransform
---@field OwningAIController ABaseAIController
---@field WeaponClass UClass
