---@class BP_Other_CompoundBow_C:BP_ShootWeaponBowBase_C
---@field GetWeaponScopeMesh:fun(socketName:FName):UMeshComponent
---@field CheckIsOverShoulder:fun():bool
---@field OverShoulder:fun(bState:bool):bool
---@field PoseStateChange:fun(State:ESTEPoseState):bool
---@field ResetVehicleAccumulateList:fun()
---@field HandleAvatarChange:fun(AsyncLoadID:int32,LoadEventFrom:UAvatarComponent)
---@field ResetHitEffect:fun()
---@field ResetMagMeshMat:fun()
---@field UpdateBowAccumulateEnergy:fun()
---@field SetMagMat:fun(LoadObject:UObject)
---@field SetMagStMesh:fun(LoadObject:UObject)
---@field SetHitEffectDataAsset:fun(LoadObject:UObject)
---@field CustomWeaponPartsEquipped:fun(WeaponSlotID:int32,IsEquipped:bool)
---@field GetLocalBulletLaunchGravityScale:fun():float
---@field GetLocalBulletLaunchtMaxNoGravityRange:fun():float
---@field GetMaxNoGravityRangeOverride:fun(ShootID:int32):float,bool
---@field GetLaunchGravityScaleOverride:fun(ShootID:int32):float,bool
---@field GetMaxBulletFireSpeed:fun():float
---@field RefreshVehicleAnimListADS:fun()
---@field DelayRefreshVehicleAccumulateList:fun()
---@field GetCurrentVehicleWeaponAnimList:fun(Character:ASTExtraBaseCharacter,Vehicle:ASTExtraVehicleBase):UUAECharAnimListCompBase
---@field ClearVehicleAnimCache:fun()
---@field InitVehicleWeaponAnimList:fun():bool
---@field RefreshVehicldeAnimListState:fun(Character:ASTExtraBaseCharacter)
---@field RefreshReloadAnim:fun()
---@field ClearAllAnimListState:fun()
---@field HandleWeaponChangeState:fun(NewState:EFreshWeaponStateType)
---@field DelayUpdateAccumulateAnimListByState:fun()
---@field OnLeaveBowAccumulateEnergyState:fun()
---@field OnEnterBowAccumulateEnergyState:fun()
---@field UnEquipReleaseAid:fun()
---@field EquipReleaseAid:fun()
---@field UpdateAnimListByState:fun(State:DefinedEnum_AnimListState,IsAdd:bool)
---@field UpdateAnimList:fun()
---@field GetBulletFireSpeedFromEntity:fun(ShootID:int32):float
---@field GetOwnerSTPlayer:fun():ASTExtraBaseCharacter
---@field ShowMag:fun(Visible:bool,Force:bool)
---@field BlueprintShouldFoldHand:fun():bool,bool
---@field OnEquipBow:fun()
---@field RefreshAnimListState:fun(Character:ASTExtraBaseCharacter)
---@field StartFireFilter:fun():bool
---@field CheckGunCollision:fun(StartCheckLoc:FVector,OutHit:FHitResult):FVector,bool
---@field OnUnEquipBow:fun()
---@field OnArrowShooted:fun()
---@field UserConstructionScript:fun()
---@field OnPushTrigger:fun()
---@field OnReleaseTrigger:fun()
---@field OnWeaponMagOut:fun()
---@field OnWeaponMagIn:fun()
---@field InitProxyBP:fun(OwnerTarget:AActor)
---@field StartFire:fun()
---@field ReceiveEndPlay:fun(EndPlayReason:EEndPlayReason)
---@field ChangeSequenceStateInner:fun(LastStateType:EFreshWeaponStateType)
---@field BP_WeaponShovelCameraModify BP_WeaponShovelCameraModify_C
---@field ReplaceSTMesh UStaticMeshComponent
---@field WeaponAnimList_Other_CompoundBow_ADS_FullBow WeaponAnimList_Other_CompoundBow_ADS_FullBow_C
---@field WeaponAnimList_Other_CompoundBow_FullBow WeaponAnimList_Other_CompoundBow_FullBow_C
---@field WeaponAnimList_Other_CompoundBow_ADS WeaponAnimList_Other_CompoundBow_ADS_C
---@field BP_CompoundBowPostFireState BP_CompoundBowPostFireState_C
---@field WeaponAnimList_Other_CompoundBow WeaponAnimList_Other_CompoundBow_C
---@field WeaponTriggerEventHandleEnergyBow UWeaponTriggerEventHandleEnergyBow
---@field BowAccumulateEnergyState UBowAccumulateEnergyState
---@field BowEnergyAccumulate UBowEnergyAccumulateComponent
---@field ST_Mag UStaticMeshComponent
---@field bUseIdleAnim_0_0 bool
---@field IsOverShoulder_0 bool
---@field IsProne bool
---@field IsProhibitIcon bool
---@field OverShoulderStand FCameraOffsetData
---@field OverShoulderCrouch FCameraOffsetData
---@field EnableAccEnergyPawnStateList ULuaArrayHelper
---@field BulletSpeedCurve_0 UCurveFloat
---@field LastFireAccTime float
---@field FullBowAnimListActive bool
---@field DeleyEnterFullBowAnimList FTimerHandle
---@field DelayLeaveFulBowAnimList FTimerHandle
---@field ADSBowAnimListActive bool
---@field ExplosionEffectTemplate UClass
---@field ADSFullBowAnimListActive bool
---@field CurAnimListState DefinedEnum_AnimListState
---@field ReleaseAidSkMesh UClass
---@field ReleaseAidActor AActor
---@field AddtiveFOV float
---@field AddtiveFOVSpeed float
---@field PendingLeaveState DefinedEnum_AnimListState
---@field AddtiveFOVCloseSpeed float
---@field AddtiveCurve UCurveFloat
---@field AddtiveFOVCloseDelayTime float
---@field IsAttachedToArrow bool
---@field IsAccumulateEnergy bool
---@field ShouldRecoveryAccumulateAnim bool
---@field CacheVehicleAnimList_CompoundBow_FullBow UUAECharAnimListCompBase
---@field CacheVehicleAnimList_CompoundBow_ADS UUAECharAnimListCompBase
---@field IsInitVehicleWeaponAnimList bool
---@field DelayEnterVehicleFullBowAnimList FTimerHandle
---@field DelayLeaveVehicleFullBowAnimList FTimerHandle
---@field FullBowVehicleAnimListActive bool
---@field ADSBowVehicleAnimListActive bool
---@field BulletGravityCurve UCurveFloat
---@field MaxNoGravityDisCurve UCurveFloat
---@field LastFireAccPercent float
---@field CachedWeaponFullBowSoundPlayID int32
---@field UpdateAccumulateEnergyTimerHandle FTimerHandle
---@field IsPostFullBowAkEvent bool
---@field CharacterSeatIndex int32
