---@class BP_Sniper_MK12_C:BP_ShootWeaponBase_C
---@field UserConstructionScript:fun()
---@field WeaponAnimList_Sniper_MK12 WeaponAnimList_Sniper_MK12_C
---@field Arrow1 UArrowComponent
---@field bUseIdleAnim_0_0 bool
