---@class Resort_Building_03_House_C:BP_UGCMobileHouseBase_C
---@field UserConstructionScript:fun()
---@field ChildActor11 UChildActorComponent
---@field ChildActor10 UChildActorComponent
---@field ChildActor9 UChildActorComponent
---@field ChildActor8 UChildActorComponent
---@field ChildActor7 UChildActorComponent
---@field ChildActor6 UChildActorComponent
---@field ChildActor5 UChildActorComponent
---@field ChildActor4 UChildActorComponent
---@field ChildActor3 UChildActorComponent
---@field ChildActor2 UChildActorComponent
---@field ChildActor1 UChildActorComponent
---@field ChildActor UChildActorComponent
---@field StaticMesh UStaticMeshComponent
