---@class bp_setting_selection_C:ALuaClassObj
---@field UserConstructionScript:fun()
---@field Generated_ScriptContext UScriptContextComponent
---@field BP_ARRAY_SettingSelectionItemList ULuaArrayHelper
