---@class BP_UAZ01_BattleItemHandle_LFLS1_C:UBackpackVehicleHandle
---@field ParticleSoftWrapperMap ULuaMapHelper
---@field Sfx_EngineLoop UAkAudioEvent
---@field Sfx_EngineLoop_Team UAkAudioEvent
---@field Sfx_Horn UAkAudioEvent
---@field Sfx_EngineStop UAkAudioEvent
---@field Sfx_enginestart UAkAudioEvent
---@field Sfx_Fireloop UAkAudioEvent
---@field Sfx_explosion UAkAudioEvent
---@field Sfx_GearUp UAkAudioEvent
---@field Sfx_GearDown UAkAudioEvent
---@field Sfx_PopKartAccelerate UAkAudioEvent
---@field PS_explosion UParticleSystem
---@field sfx_throttle UAkAudioEvent
---@field sfx_boost UAkAudioEvent
---@field PlumesmokeTemplate UParticleSystem
---@field Sfx_SiblingSwitch UAkAudioEvent
