---@class BPTask_KillingInCityP_C:UUAETriggerObject_KillPlayer
---@field ConstructActions:fun():ULuaArrayHelper
---@field ConstructConditions:fun():UTriggerCondition
---@field ConstructEvents:fun():ULuaArrayHelper
