---@class BPTask_DancingAtSpecifiedPosition_C:UUAETriggerObject_Task
---@field ConstructActions:fun():ULuaArrayHelper
---@field ConstructConditions:fun():UTriggerCondition
---@field ConstructEvents:fun():ULuaArrayHelper
---@field Condition_SpecifiedPlace UTriggerCondition
---@field Condition_SpecifiedItem UTriggerCondition
