---@class BPTask_TeamDancingInArea_C:UUAETriggerObject_Task
---@field ConstructActions:fun():ULuaArrayHelper
---@field ConstructConditions:fun():UTriggerCondition
---@field ConstructEvents:fun():ULuaArrayHelper
