---@class ParachutingControlNewbieGuide_Tips01_UIBP_C:UNewbieGuideWidget
---@field OnCreateAndShow:fun(GuideId:int32,UIConfigIndex:int32)
---@field UTRichTextBlock_Tips16_Text1 UUTRichTextBlock
---@field CountDownTime float
---@field IsCountDown bool
---@field CacheLeaderPlayerState ASTExtraPlayerState
