---@meta

---@class UAISenseConfig: UObject
---@field DebugColor FColor
---@field MaxAge number @specifies age limit after stimuli generated by this sense become forgotten. 0 means "never"
---@field bStartsEnabled number @determines whether given sense starts in an enabled state
local UAISenseConfig = {}
