---@meta

---@class EAndroidAntVerbosity
---@field Quiet number @Extra quiet logging (-quiet), errors will be logged by second run at normal verbosity.
---@field Normal number @Normal logging (no options)
---@field Verbose number @Extra verbose logging (-verbose)
EAndroidAntVerbosity = {}


---@class EAndroidScreenOrientation
---@field Portrait number @Portrait orientation (the display is taller than it is wide).
---@field ReversePortrait number @Portrait orientation rotated 180 degrees.
---@field SensorPortrait number @Use either portrait or reverse portrait orientation, where supported by the device, based on the device orientation sensor.
---@field Landscape number @Landscape orientation (the display is wider than it is tall).
---@field ReverseLandscape number @Landscape orientation rotated 180 degrees.
---@field SensorLandscape number @Use either landscape or reverse landscape orientation, based on the device orientation sensor.
---@field Sensor number @Use any orientation the device normally supports, based on the device orientation sensor.
---@field FullSensor number @Use any orientation (including ones the device wouldn't choose in Sensor mode), based on the device orientation sensor.
EAndroidScreenOrientation = {}


---Depth buffer precision preferences
---@class EAndroidDepthBufferPreference
---@field Default number @Default
---@field Bits16 number @16-bit
---@field Bits24 number @24-bit
---@field Bits32 number @32-bit
EAndroidDepthBufferPreference = {}


---The default install location for the application
---@class EAndroidInstallLocation
---@field InternalOnly number @Install your app only on internal device storage
---@field PreferExternal number @Install your app on external storage when available
---@field Auto number @Internal storage is preferred over external, unless the interal storage is low on space
EAndroidInstallLocation = {}


---@class EAndroidAudio
---@field Default number @Default
---@field OGG number @Ogg Vorbis
---@field ADPCM number @ADPCM
EAndroidAudio = {}


---@class EGoogleVRMode
---@field Cardboard number @Cardboard
---@field Daydream number @Daydream
---@field DaydreamAndCardboard number @Daydream & Cardboard
EGoogleVRMode = {}


---@class EGoogleVRCaps
---@field Cardboard number @Cardboard
---@field Daydream33 number @Daydream (3.3 DoF)
---@field Daydream63 number @Daydream (6.3 DoF)
EGoogleVRCaps = {}


---@class EAndroidGraphicsDebugger
---@field None number @None
---@field Mali number @Mali Graphics Debugger
---@field Adreno number @Adreno Profiler
---@field RenderDoc number @RenderDoc (Experimental)
EAndroidGraphicsDebugger = {}


---Holds the game-specific achievement name and corresponding ID from Google Play services.
---@class FGooglePlayAchievementMapping
---@field Name string @The game-specific achievement name (the one passed in to WriteAchievement calls).
---@field AchievementID string @The ID of the corresponding achievement, generated by the Google Play developer console.
FGooglePlayAchievementMapping = {}


---Holds the game-specific leaderboard name and corresponding ID from Google Play services.
---@class FGooglePlayLeaderboardMapping
---@field Name string @The game-specific leaderboard name (the one passed in to WriteLeaderboards calls).
---@field LeaderboardID string @The ID of the corresponding leaderboard, generated by the Google Play developer console.
FGooglePlayLeaderboardMapping = {}


---Implements the settings for the Android runtime platform.
---@class UAndroidRuntimeSettings: UObject
---@field PackageName string
---@field StoreVersion number
---@field ApplicationDisplayName string
---@field VersionDisplayName string
---@field MinSDKVersion number
---@field TargetSDKVersion number
---@field InstallLocation EAndroidInstallLocation
---@field bEnableGradle boolean
---@field bPackageDataInsideApk boolean
---@field bCreateAllPlatformsInstall boolean
---@field bDisableVerifyOBBOnStartUp boolean
---@field bUseExternalFilesDir boolean
---@field Orientation EAndroidScreenOrientation
---@field MaxAspectRatio number
---@field AntVerbosity EAndroidAntVerbosity
---@field bFullScreen boolean
---@field bEnableNewKeyboard boolean
---@field DepthBufferPreference EAndroidDepthBufferPreference
---@field ExtraManifestNodeTags ULuaArrayHelper<string>
---@field ExtraApplicationNodeTags ULuaArrayHelper<string>
---@field ExtraApplicationSettings string
---@field ExtraActivityNodeTags ULuaArrayHelper<string>
---@field ExtraActivitySettings string
---@field ExtraPermissions ULuaArrayHelper<string>
---@field bAndroidVoiceEnabled boolean
---@field bPackageForGearVR boolean
---@field bRemoveOSIG boolean
---@field GoogleVRCaps ULuaArrayHelper<EGoogleVRCaps>
---@field bGoogleVRSustainedPerformance boolean
---@field KeyStore string
---@field KeyAlias string
---@field KeyStorePassword string
---@field KeyPassword string
---@field bBuildForArmV7 boolean
---@field bBuildForArm64 boolean
---@field bBuildForX86 boolean
---@field bBuildForX8664 boolean
---@field bBuildForES2 boolean
---@field bBuildForES31 boolean
---@field bSupportsVulkan boolean
---@field bBuildWithHiddenSymbolVisibility boolean
---@field bEnableGooglePlaySupport boolean
---@field bUseGetAccounts boolean
---@field GamesAppID string
---@field AchievementMap ULuaArrayHelper<FGooglePlayAchievementMapping>
---@field LeaderboardMap ULuaArrayHelper<FGooglePlayLeaderboardMapping>
---@field bSupportAdMob boolean
---@field AdMobAdUnitID string
---@field AdMobAdUnitIDs ULuaArrayHelper<string>
---@field GooglePlayLicenseKey string
---@field GCMClientSenderID string
---@field bShowLaunchImage boolean @Show the launch image as a startup slash screen
---@field AndroidAudio EAndroidAudio @Android encoding options.
---@field AudioSampleRate number @Sample rate to run the audio mixer with.
---@field AudioCallbackBufferFrameSize number @The amount of audio to compute each callback block. Lower values decrease latency but may increase CPU cost.
---@field AudioNumBuffersToEnqueue number @The number of buffers to keep enqueued. More buffers increases latency, but can compensate for variable compute availability in audio callbacks on some platforms.
---@field AudioMaxChannels number @The max number of channels (voices) to limit for this platform. The max channels used will be the minimum of this value and the global audio quality settings. A value of 0 will not apply a platform channel count max.
---@field AudioNumSourceWorkers number @The number of workers to use to compute source audio. Will only use up to the max number of sources. Will evenly divide sources to each source worker.
---@field SpatializationPlugin string @Which of the currently enabled spatialization plugins to use on Windows.
---@field ReverbPlugin string @Which of the currently enabled reverb plugins to use on Windows.
---@field OcclusionPlugin string @Which of the currently enabled occlusion plugins to use on Windows.
---@field AndroidGraphicsDebugger EAndroidGraphicsDebugger
---@field MaliGraphicsDebuggerPath FDirectoryPath @The path to your Mali Graphics Debugger installation (eg C:/Program Files/ARM/Mali Developer Tools/Mali Graphics Debugger v4.2.0)
---@field RenderDocPath FDirectoryPath @The path to your RenderDoc installation (eg C:/Program Files/RenderDoc)
---@field bMultiTargetFormat_ETC1 boolean @Include ETC1 textures when packaging with the Android (Multi) variant. ETC1 will be included if no other formats are selected.
---@field bMultiTargetFormat_ETC2 boolean @Include ETC2 textures when packaging with the Android (Multi) variant.
---@field bMultiTargetFormat_DXT boolean @Include DXT textures when packaging with the Android (Multi) variant.
---@field bMultiTargetFormat_PVRTC boolean @Include PVRTC textures when packaging with the Android (Multi) variant.
---@field bMultiTargetFormat_ATC boolean @Include ATC textures when packaging with the Android (Multi) variant.
---@field bMultiTargetFormat_ASTC boolean @Include ASTC textures when packaging with the Android (Multi) variant.
---@field TextureFormatPriority_ETC1 number @Priority for the ETC1 texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.1.
---@field TextureFormatPriority_ETC2 number @Priority for the ETC2 texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.2.
---@field TextureFormatPriority_DXT number @Priority for the DXT texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.6.
---@field TextureFormatPriority_PVRTC number @Priority for the PVRTC texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.8.
---@field TextureFormatPriority_ATC number @Priority for the ATC texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.5.
---@field TextureFormatPriority_ASTC number @Priority for the ASTC texture format when launching on device or packaging using Android_Multi. The highest priority format supported by the device will be used. Default value is 0.9.
local UAndroidRuntimeSettings = {}
