---@meta

---@class ECopyMotion_Component
---@field TranslationX number
---@field TranslationY number
---@field TranslationZ number
---@field RotationAngle number
ECopyMotion_Component = {}


---@class FAnimNode_CopyMotion
---@field BasePose FComponentSpacePoseLink
---@field BasePoseReference FComponentSpacePoseLink
---@field bUseBasePose boolean
---@field PoseHistoryTag string
---@field Delay number
---@field SourceBone FBoneReference
---@field BoneToModify FBoneReference @Name of bone to control. This is the main bone chain to modify from. *
---@field CopySpace FBoneReference @Bone to use as the reference frame/space for our copied transform delta. If no reference frame is used, the source bone motion will be copied in component space.
---@field ApplySpace FBoneReference @Bone to use as the reference frame/space for our applied transform delta. If no reference frame is used, the source bone motion will be applied in component space.
---@field TranslationOffset FRotator @Offset to use before applying the translation deltas (in degrees). This is useful for changing the direction of motion, relative to our reference frame/bone
---@field RotationOffset FRotator @Rotation offset (in degrees) to apply before the rotation deltas. This is useful for changing the direction of motion, relative to our reference frame/bone
---@field RotationPivot FVector @Pivot offset (in local space) to use when applying the rotation. Any non-zero value will cause the target bone to rotate around the pivot, effectively introducing additional translation.
---@field CurvePrefix string @Curve prefix used for the animation curves. Format matches those generated by the LayeringMotionExtractorModifier
---@field TargetCurveName string @Name of the curve we're outputting motion to.
---@field TargetCurveScale number @Which component of motion we're outputting to the curve.
---@field TargetCurveComponent ECopyMotion_Component @Which component of motion we're outputting to the curve.
---@field TargetCurveRotationAxis EAxis @Axis around which to consider the rotation angle for the curve output.
---@field TranslationX_CurveName string
---@field TranslationY_CurveName string
---@field TranslationZ_CurveName string
---@field RotationRoll_CurveName string
---@field RotationPitch_CurveName string
---@field RotationYaw_CurveName string
---@field TranslationScale FVector
---@field RotationScale number
FAnimNode_CopyMotion = {}


---@class UCopyMotionMathLibrary: UBlueprintFunctionLibrary
local UCopyMotionMathLibrary = {}
