---@meta

---Enumerates states a blueprint can be in.
---@class EBlueprintStatus
---@field BS_Unknown number @Blueprint is in an unknown state.
---@field BS_Dirty number @Blueprint has been modified but not recompiled.
---@field BS_Error number @Blueprint tried but failed to be compiled.
---@field BS_UpToDate number @Blueprint has been compiled since it was last modified.
---@field BS_BeingCreated number @Blueprint is in the process of being created for the first time.
---@field BS_UpToDateWithWarnings number @Blueprint has been compiled since it was last modified. There are warnings.
---@field BS_MAX number
EBlueprintStatus = {}


---Enumerates types of blueprints.
---@class EBlueprintType
---@field BPTYPE_Normal number @Normal blueprint.
---@field BPTYPE_Const number @Blueprint that is const during execution (no state graph and methods cannot modify member variables).
---@field BPTYPE_MacroLibrary number @Blueprint that serves as a container for macros to be used in other blueprints.
---@field BPTYPE_Interface number @Blueprint that serves as an interface to be implemented by other blueprints.
---@field BPTYPE_LevelScript number @Blueprint that handles level scripting.
---@field BPTYPE_FunctionLibrary number @Blueprint that serves as a container for functions to be used in other blueprints.
---@field BPTYPE_MAX number
EBlueprintType = {}


---Compile modes.
---@class EBlueprintCompileMode
---@field Default number @Use Default
---@field Development number
---@field FinalRelease number
EBlueprintCompileMode = {}


---@class EVariableMetaDataFlag
---@field Default number
---@field ArrayInner number
---@field SetElem number
---@field MapKey number
---@field MapValue number
EVariableMetaDataFlag = {}


---@class EBlueprintNativizationFlag
---@field Disabled number
---@field Dependency number
---@field ExplicitlyEnabled number
EBlueprintNativizationFlag = {}


---@class FCompilerNativizationOptions
---@field PlatformName string
---@field ServerOnlyPlatform boolean
---@field ClientOnlyPlatform boolean
---@field ExcludedModules ULuaArrayHelper<string>
---@field ExcludedAssets ULuaSetHelper<FSoftObjectPath>
---@field ExcludedFolderPaths ULuaArrayHelper<string>
FCompilerNativizationOptions = {}


---Cached 'cosmetic' information about a macro graph (this is transient and is computed at load)
---@class FBlueprintMacroCosmeticInfo
FBlueprintMacroCosmeticInfo = {}


---One metadata entry for a variable
---@class FBPVariableMetaDataEntry
---@field DataKey string @Name of metadata key
---@field DataValue string @Name of metadata value
---@field Flag EVariableMetaDataFlag
FBPVariableMetaDataEntry = {}


---Struct indicating a variable in the generated class
---@class FBPVariableDescription
---@field VarName string @Name of the variable
---@field VarGuid FGuid @A Guid that will remain constant even if the VarName changes
---@field VarType any @Type of the variable
---@field FriendlyName string @Friendly name of the variable
---@field Category string @Category this variable should be in
---@field PropertyFlags number @Property flags for this variable - Changed from int32 to uint64
---@field RepNotifyFunc string
---@field ReplicationCondition ELifetimeCondition
---@field MetaDataArray ULuaArrayHelper<FBPVariableMetaDataEntry> @Metadata information for this variable
---@field DefaultValue string @Optional new default value stored as string
FBPVariableDescription = {}


---Struct containing information about what interfaces are implemented in this blueprint
---@class FBPInterfaceDescription
---@field Interface UInterface @Reference to the interface class we're adding to this blueprint
---@field Graphs ULuaArrayHelper<UEdGraph> @References to the graphs associated with the required functions for this interface
FBPInterfaceDescription = {}


---@class FEditedDocumentInfo
---@field SavedViewOffset FVector2D @Saved view position
---@field SavedZoomAmount number @Saved zoom amount
FEditedDocumentInfo = {}


---Blueprints are special assets that provide an intuitive, node-based interface that can be used to create new types of Actors and script level events; giving designers and gameplay programmers the tools to quickly create and iterate gameplay from within Unreal Editor without ever needing to write a line of code.
---@class UBlueprint: UBlueprintCore
---@field bRecompileOnLoad number @Whether or not this blueprint should recompile itself on load
---@field ParentClass UObject @Pointer to the parent class that the generated class should derive from. This *can* be null under rare circumstances, one such case can be created by creating a blueprint (A) based on another blueprint (B), shutting down the editor, and deleting the parent blueprint.
---@field bHasBeenRegenerated number @When the class generated by this blueprint is loaded, it will be recompiled the first time.  After that initial recompile, subsequent loads will skip the regeneration step
---@field bIsRegeneratingOnLoad number @State flag to indicate whether or not the Blueprint is currently being regenerated on load
---@field ComponentTemplates ULuaArrayHelper<UActorComponent> @Array of component template objects, used by AddComponent function
---@field Timelines ULuaArrayHelper<UTimelineTemplate> @Array of templates for timelines that should be created
---@field BlueprintType EBlueprintType @The type of this blueprint
---@field BlueprintSystemVersion number @The version of the blueprint system that was used to  create this blueprint
---@field bNativize_DEPRECATED boolean @Deprecated properties.
local UBlueprint = {}
