---@meta

---@class UBlueprintCore: UObject
---@field SkeletonGeneratedClass UObject @Pointer to the skeleton class; this is regenerated any time a member variable or function is added but is usually incomplete (no code or hidden autogenerated variables are added to it)
---@field GeneratedClass UObject @Pointer to the 'most recent' fully generated class
---@field bLegacyNeedToPurgeSkelRefs boolean @BackCompat:  Whether or not we need to purge references in this blueprint to the skeleton generated during compile-on-load
---@field bLegacyGeneratedClassIsAuthoritative boolean @BackCompat: Whether or not this blueprint's authoritative CDO data has been migrated from the SkeletonGeneratedClass CDO to the GeneratedClass CDO
---@field BlueprintGuid FGuid @Blueprint Guid
local UBlueprintCore = {}
