---@meta

---@class EBlueprintPinStyleType
---@field BPST_Original number @Circles, Grid, Diamond
---@field BPST_VariantA number @Directional Circles
EBlueprintPinStyleType = {}


---@class FSimpleMemberReference
---@field MemberName string @Name of the member
---@field MemberGuid FGuid @The Guid of the member
FSimpleMemberReference = {}


---Struct used to define the type of information carried on this pin
---@class FEdGraphPinType
---@field PinCategory string @Category of pin type
---@field PinSubCategory string @Sub-category of pin type
---@field PinSubCategoryObject UObject @Sub-category object
---@field PinSubCategoryMemberReference FSimpleMemberReference @Sub-category member reference
---@field PinValueType FEdGraphTerminalType @Data used to determine value types when bIsMap is true
---@field ContainerType EPinContainerType
---@field bIsArray_DEPRECATED number @DEPRECATED(4.17) Whether or not this pin represents an array of values
---@field bIsReference number @Whether or not this pin is a value passed by reference or not
---@field bIsConst number @Whether or not this pin is a immutable const value
---@field bIsWeakPointer number @Whether or not this is a weak reference
FEdGraphPinType = {}


---@class FEdGraphPinReference
---@field OwningNode UEdGraphNode @The node that owns the pin referred to by this struct. Updated at Set and Save time.
---@field PinId FGuid @The pin's unique ID. Updated at Set and Save time.
FEdGraphPinReference = {}


---@class UEdGraphPin_Deprecated: UObject
---@field PinName string @Name of this pin
---@field PinToolTip string @The tool-tip describing this pin's purpose
---@field Direction EEdGraphPinDirection @Direction of flow of this pin (input or output)
---@field PinType any @The type of information carried on this pin
---@field DefaultValue string @Default value for this pin (used if the pin has no connections), stored as a string
---@field AutogeneratedDefaultValue string @Initial default value (the autogenerated value, to identify if the user has modified the value), stored as a string
---@field DefaultTextValue string @If the default value for this pin should be an FText, it is stored here.
---@field LinkedTo ULuaArrayHelper<UEdGraphPin_Deprecated> @Set of pins that we are linked to
---@field SubPins ULuaArrayHelper<UEdGraphPin_Deprecated> @The pins created when a pin is split and hidden
local UEdGraphPin_Deprecated = {}
