---@meta

---@class UEnvQueryInstanceBlueprintWrapper: UObject, IEQSQueryResultSourceInterface
---@field QueryID number
---@field ItemType UEnvQueryItemType
---@field OptionIndex number @index of query option, that generated items
---@field OnQueryFinishedEvent FEQSQueryDoneSignature
local UEnvQueryInstanceBlueprintWrapper = {}

---@param ItemIndex number
---@return number
function UEnvQueryInstanceBlueprintWrapper:GetItemScore(ItemIndex) end

---return an array filled with resulting actors. Note that it makes sense only if ItemType is a EnvQueryItemType_ActorBase-derived type
function UEnvQueryInstanceBlueprintWrapper:GetResultsAsActors() end

---returns an array of locations generated by the query. If the query generated Actors the the array is filled with their locations
function UEnvQueryInstanceBlueprintWrapper:GetResultsAsLocations() end

---@param ParamName string
---@param Value number
function UEnvQueryInstanceBlueprintWrapper:SetNamedParam(ParamName, Value) end
