---@meta

---called when we finish playing forcefeedback effect, either because it played to completion or because a Stop() call turned it off early
---@class FOnForceFeedbackFinished : ULuaMulticastDelegate
FOnForceFeedbackFinished = {}

---添加回调，Func 作为 Key 去重，同 Func 不同 Obj 会覆盖
---@param Callback fun(Obj: any, ForceFeedbackComponent: UForceFeedbackComponent) @回调函数
---@param Obj any @可选的绑定对象，作为回调第一个参数传入
---@return number @回调引用
function FOnForceFeedbackFinished:Add(Callback, Obj) end

---触发 Lua 广播
---@param ForceFeedbackComponent UForceFeedbackComponent
function FOnForceFeedbackFinished:Broadcast(ForceFeedbackComponent) end


---ForceFeedbackComponent allows placing a rumble effect in to the world and having it apply to player characters who come near it
---@class UForceFeedbackComponent: USceneComponent
---@field bAutoDestroy number @Auto destroy this component on completion
---@field bStopWhenOwnerDestroyed number @Stop effect when owner is destroyed
---@field bLooping number
---@field bIgnoreTimeDilation number @Should the playback of the forcefeedback pattern ignore time dilation and use the app's delta time
---@field bOverrideAttenuation number @Should the Attenuation Settings asset be used (false) or should the properties set directly on the component be used for attenuation properties
---@field IntensityMultiplier number @The intensity multiplier to apply to effects generated by this component
---@field AttenuationOverrides any @If bOverrideSettings is true, the attenuation properties to use for effects generated by this component
---@field OnForceFeedbackFinished FOnForceFeedbackFinished @called when we finish playing audio, either because it played to completion or because a Stop() call turned it off early
local UForceFeedbackComponent = {}

---Set what force feedback effect is played by this component
---@param NewForceFeedbackEffect UForceFeedbackEffect
function UForceFeedbackComponent:SetForceFeedbackEffect(NewForceFeedbackEffect) end

---Start a feedback effect playing
---@param StartTime number
function UForceFeedbackComponent:Play(StartTime) end

---Stop playing the feedback effect
function UForceFeedbackComponent:Stop() end

---Set a new intensity multiplier
---@param NewIntensityMultiplier number
function UForceFeedbackComponent:SetIntensityMultiplier(NewIntensityMultiplier) end

---Modify the attenuation settings of the component
---@param InAttenuationSettings FForceFeedbackAttenuationSettings
function UForceFeedbackComponent:AdjustAttenuation(InAttenuationSettings) end

---@param OutAttenuationSettings FForceFeedbackAttenuationSettings
---@return boolean
function UForceFeedbackComponent:BP_GetAttenuationSettingsToApply(OutAttenuationSettings) end
