---@meta

---ALevelScriptActor is the base class for classes generated by ULevelScriptBlueprints. ALevelScriptActor instances are hidden actors that exist within a level, and can execute level-wide logic (operating on specific actor instances within the level). The level-script's functionality is defined inside the ULevelScriptBlueprint itself (using the blueprint's node-based interface).
---@class ALevelScriptActor: AActor
---@field bInputEnabled number
local ALevelScriptActor = {}

---Tries to find an event named "EventName" on all other levels, and calls it
---@param EventName string
---@return boolean
function ALevelScriptActor:RemoteEvent(EventName) end

---Sets the cinematic mode on all PlayerControllers
---@param bCinematicMode boolean
---@param bHidePlayer boolean
---@param bAffectsHUD boolean
---@param bAffectsMovement boolean
---@param bAffectsTurning boolean
function ALevelScriptActor:SetCinematicMode(bCinematicMode, bHidePlayer, bAffectsHUD, bAffectsMovement, bAffectsTurning) end

function ALevelScriptActor:LevelReset() end

---Event called on world origin location changes
---@param OldOriginLocation FIntVector
---@param NewOriginLocation FIntVector
function ALevelScriptActor:WorldOriginLocationChanged(OldOriginLocation, NewOriginLocation) end
