---@meta

---LODActor is an instance of an autogenerated StaticMesh Actors by Hierarchical LOD System This is essentially just StaticMeshActor that you can't move or edit, but it contains multiple actors reference
---@class ALODActor: AActor
---@field Key string @The key used to validate this actor against the proxy
---@field LODDrawDistance number @what distance do you want this to show up instead of SubActors
---@field SubActors ULuaArrayHelper<AActor>
---@field LODLevel number @The hierarchy level of this actor; the first tier of HLOD is level 1, the second tier is level 2 and so on.
---@field CachedNumHLODLevels number
local ALODActor = {}
