---@meta

---Enum for specifying type of a name instance parameter.
---@class EParticleSysParamType
---@field PSPT_None number @None
---@field PSPT_Scalar number @Scalar
---@field PSPT_ScalarRand number @Scalar Random
---@field PSPT_Vector number @Vector
---@field PSPT_VectorRand number @Vector Random
---@field PSPT_Color number @Color
---@field PSPT_Actor number @Actor
---@field PSPT_Material number @Material
---@field PSPT_MAX number
EParticleSysParamType = {}


---Particle system replay state
---@class ParticleReplayState
---@field PRS_Disabled number @Replay system is disabled.  Particles are simulated and rendered normally.
---@field PRS_Capturing number @Capture all particle data to the clip specified by ReplayClipIDNumber.  The frame to capture must be specified using the ReplayFrameIndex
---@field PRS_Replaying number @Replay captured particle state from the clip specified by ReplayClipIDNumber.  The frame to play must be specified using the ReplayFrameIndex
---@field PRS_MAX number
ParticleReplayState = {}


---Event type
---@class EParticleEventType
---@field EPET_Any number @Any - allow any event
---@field EPET_Spawn number @Spawn - a particle spawn event
---@field EPET_Death number @Death - a particle death event
---@field EPET_Collision number @Collision - a particle collision event
---@field EPET_Burst number @Burst - a particle burst event
---@field EPET_Blueprint number @Blueprint - an event generated by level script
---@field EPET_MAX number
EParticleEventType = {}


---@class EParticleTemplateBindingType
---@field ParticleSystem number
---@field SoftParticleSystem number
EParticleTemplateBindingType = {}


---Struct used for a particular named instance parameter for this ParticleSystemComponent.
---@class FParticleSysParam
---@field Name string @The name of the parameter
---@field ParamType EParticleSysParamType @The type of parameters PSPT_None       - There is no data type PSPT_Scalar     - Use the scalar value PSPT_ScalarRand - Select a scalar value in the range [Scalar_Low..Scalar) PSPT_Vector     - Use the vector value PSPT_VectorRand - Select a vector value in the range [Vector_Low..Vector) PSPT_Color      - Use the color value PSPT_Actor      - Use the actor value PSPT_Material   - Use the material value
---@field Scalar number
---@field Scalar_Low number
---@field Vector FVector
---@field Vector_Low FVector
---@field Color FColor
FParticleSysParam = {}


---@class FOnSystemFinished : ULuaMulticastDelegate
FOnSystemFinished = {}

---添加回调，Func 作为 Key 去重，同 Func 不同 Obj 会覆盖
---@param Callback fun(Obj: any, PSystem: UParticleSystemComponent) @回调函数
---@param Obj any @可选的绑定对象，作为回调第一个参数传入
---@return number @回调引用
function FOnSystemFinished:Add(Callback, Obj) end

---触发 Lua 广播
---@param PSystem UParticleSystemComponent
function FOnSystemFinished:Broadcast(PSystem) end


---@class FOnSystemPreActivationChange : ULuaMulticastDelegate
FOnSystemPreActivationChange = {}

---添加回调，Func 作为 Key 去重，同 Func 不同 Obj 会覆盖
---@param Callback fun(Obj: any, Param1: UParticleSystemComponent, Param2: boolean) @回调函数
---@param Obj any @可选的绑定对象，作为回调第一个参数传入
---@return number @回调引用
function FOnSystemPreActivationChange:Add(Callback, Obj) end

---触发 Lua 广播
---@param Param1 UParticleSystemComponent
---@param Param2 boolean
function FOnSystemPreActivationChange:Broadcast(Param1, Param2) end


---A particle emitter.
---@class UParticleSystemComponent: UPrimitiveComponent, IWTACAggregateInterface, IObjectPoolInterface
---@field TemplateBindingType EParticleTemplateBindingType
---@field SoftTemplate UParticleSystem
---@field EmitterMaterials ULuaArrayHelper<UMaterialInterface>
---@field SkelMeshComponents ULuaArrayHelper<USkeletalMeshComponent> @The skeletal mesh components used with the socket location module. This is to prevent them from being garbage collected.
---@field bResetOnDetach number
---@field bUpdateOnDedicatedServer number @whether to update the particle system on dedicated servers
---@field bAllowRecycling number @If true, this Particle System will be available for recycling after it has completed. Auto-destroyed systems cannot be recycled. Some systems (currently particle trail effects) can recycle components to avoid respawning them to play new effects. This is only an optimization and does not change particle system behavior, aside from not triggering normal component initialization events more than once.
---@field bAutoManageAttachment number @True if we should automatically attach to AutoAttachParent when activated, and detach from our parent when completed. This overrides any current attachment that may be present at the time of activation (deferring initial attachment until activation, if AutoAttachParent is null). When enabled, detachment occurs regardless of whether AutoAttachParent is assigned, and the relative transform from the time of activation is restored. This also disables attachment on dedicated servers, where we don't actually activate even if bAutoActivate is true.
---@field bWarmingUp number
---@field bOverrideLODMethod number @indicates that the component's LODMethod overrides the Template's
---@field bSkipUpdateDynamicDataDuringTick number @Flag indicating that dynamic updating of render data should NOT occur during Tick. This is used primarily to allow for warming up and simulated effects to a certain state.
---@field LODMethod ParticleSystemLODMethod @The method of LOD level determination to utilize for this particle system
---@field RequiredSignificance EParticleSignificanceLevel @The significance this component requires of it's emitters for them to be enabled.
---@field bShouldUseTagGetSkeletalMesh boolean @Array holding name instance parameters for this ParticleSystemComponent. Parameters can be used in Cascade using DistributionFloat/VectorParticleParameters.
---@field SkeletalMeshTagName string
---@field InstanceParameters ULuaArrayHelper<FParticleSysParam>
---@field OnParticleSpawn FParticleSpawnSignature
---@field OnParticleBurst FParticleBurstSignature
---@field OnParticleDeath FParticleDeathSignature
---@field OnParticleCollide FParticleCollisionSignature
---@field OldPosition FVector
---@field PartSysVelocity FVector
---@field WarmupTime number
---@field WarmupTickRate number
---@field OverrideEmitterMeshDataMap ULuaMapHelper<string, UStaticMesh>
---@field SecondsBeforeInactive number @Number of seconds of emitter not being rendered that need to pass before it no longer gets ticked/ becomes inactive.
---@field MaxTimeBeforeForceUpdateTransform number @Time between forced UpdateTransforms for systems that use dynamically calculated bounds, Which is effectively how often the bounds are shrunk.
---@field ReplayClips ULuaArrayHelper<UParticleSystemReplay> @Array of replay clips for this particle system component.  These are serialized to disk.  You really should never add anything to this in the editor.  It's exposed so that you can delete clips if you need to, but be careful when doing so!
---@field CustomTimeDilation number @Scales DeltaTime in UParticleSystemComponent::Tick(...)
---@field bIsPCPlatformResource boolean @Is PC Redirect Particle Resource
---@field AutoAttachParent USceneComponent @Component we automatically attach to when activated, if bAutoManageAttachment is true. If null during registration, we assign the existing AttachParent and defer attachment until we activate.
---@field AutoAttachSocketName string @Socket we automatically attach to on the AutoAttachParent, if bAutoManageAttachment is true.
---@field AutoAttachLocationRule EAttachmentRule @Options for how we handle our location when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
---@field AutoAttachRotationRule EAttachmentRule @Options for how we handle our rotation when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
---@field AutoAttachScaleRule EAttachmentRule @Options for how we handle our scale when we attach to the AutoAttachParent, if bAutoManageAttachment is true.
---@field OnSystemFinished FOnSystemFinished
---@field bForceNoAsync boolean
---@field SystemFixedWorldBounds FBox
---@field SystemFixedLocalBounds FBox
---@field CollisionIgnoreActorList ULuaArrayHelper<AActor>
---@field CollisionIgnoreComponentList ULuaArrayHelper<UPrimitiveComponent>
---@field CollisionIgnoreInfoLastClearTime number
local UParticleSystemComponent = {}

---@return number
function UParticleSystemComponent:GetDuration() end

---@param WorldBounds FBox
function UParticleSystemComponent:SetSystemFixedWorldBounds(WorldBounds) end

---@param LocalBounds FBox
function UParticleSystemComponent:SetSystemFixedLocalBounds(LocalBounds) end

---Clear any previously set fixed bounds for the system instance.
function UParticleSystemComponent:ClearSystemFixedBounds() end

---@param WarmUpTime number
---@param WarmUpRate number
function UParticleSystemComponent:SetWarmUp(WarmUpTime, WarmUpRate) end

---DEPRECATED: Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationType to the specified parameters. Does not change bAutoManageAttachment; that must be set separately.
---@param Parent USceneComponent
---@param SocketName string
---@param LocationType EAttachLocation
function UParticleSystemComponent:SetAutoAttachParams(Parent, SocketName, LocationType) end

---Set AutoAttachParent, AutoAttachSocketName, AutoAttachLocationRule, AutoAttachRotationRule, AutoAttachScaleRule to the specified parameters. Does not change bAutoManageAttachment; that must be set separately.
---@param Parent USceneComponent
---@param SocketName string
---@param LocationRule EAttachmentRule
---@param RotationRule EAttachmentRule
---@param ScaleRule EAttachmentRule
function UParticleSystemComponent:SetAutoAttachmentParameters(Parent, SocketName, LocationRule, RotationRule, ScaleRule) end

---Set the beam end point
---@param EmitterIndex number
---@param NewEndPoint FVector
function UParticleSystemComponent:SetBeamEndPoint(EmitterIndex, NewEndPoint) end

---Set the beam source point
---@param EmitterIndex number
---@param NewSourcePoint FVector
---@param SourceIndex number
function UParticleSystemComponent:SetBeamSourcePoint(EmitterIndex, NewSourcePoint, SourceIndex) end

---Set the beam source tangent
---@param EmitterIndex number
---@param NewTangentPoint FVector
---@param SourceIndex number
function UParticleSystemComponent:SetBeamSourceTangent(EmitterIndex, NewTangentPoint, SourceIndex) end

---Set the beam source strength
---@param EmitterIndex number
---@param NewSourceStrength number
---@param SourceIndex number
function UParticleSystemComponent:SetBeamSourceStrength(EmitterIndex, NewSourceStrength, SourceIndex) end

---Set the beam target point
---@param EmitterIndex number
---@param NewTargetPoint FVector
---@param TargetIndex number
function UParticleSystemComponent:SetBeamTargetPoint(EmitterIndex, NewTargetPoint, TargetIndex) end

---Set the beam target tangent
---@param EmitterIndex number
---@param NewTangentPoint FVector
---@param TargetIndex number
function UParticleSystemComponent:SetBeamTargetTangent(EmitterIndex, NewTangentPoint, TargetIndex) end

---Set the beam target strength
---@param EmitterIndex number
---@param NewTargetStrength number
---@param TargetIndex number
function UParticleSystemComponent:SetBeamTargetStrength(EmitterIndex, NewTargetStrength, TargetIndex) end

---Get the beam end point false		EmitterIndex invalid or End point is not set - OutEndPoint is invalid
---@param EmitterIndex number
---@param OutEndPoint FVector
---@return boolean
function UParticleSystemComponent:GetBeamEndPoint(EmitterIndex, OutEndPoint) end

---Get the beam source point false		EmitterIndex or SourceIndex is invalid - OutSourcePoint is invalid
---@param EmitterIndex number
---@param SourceIndex number
---@param OutSourcePoint FVector
---@return boolean
function UParticleSystemComponent:GetBeamSourcePoint(EmitterIndex, SourceIndex, OutSourcePoint) end

---Get the beam source tangent false		EmitterIndex or SourceIndex is invalid - OutTangentPoint is invalid
---@param EmitterIndex number
---@param SourceIndex number
---@param OutTangentPoint FVector
---@return boolean
function UParticleSystemComponent:GetBeamSourceTangent(EmitterIndex, SourceIndex, OutTangentPoint) end

---Get the beam source strength false		EmitterIndex or SourceIndex is invalid - OutSourceStrength is invalid
---@param EmitterIndex number
---@param SourceIndex number
---@param OutSourceStrength number
---@return boolean
function UParticleSystemComponent:GetBeamSourceStrength(EmitterIndex, SourceIndex, OutSourceStrength) end

---Get the beam target point false		EmitterIndex or TargetIndex is invalid - OutTargetPoint is invalid
---@param EmitterIndex number
---@param TargetIndex number
---@param OutTargetPoint FVector
---@return boolean
function UParticleSystemComponent:GetBeamTargetPoint(EmitterIndex, TargetIndex, OutTargetPoint) end

---Get the beam target tangent false		EmitterIndex or TargetIndex is invalid - OutTangentPoint is invalid
---@param EmitterIndex number
---@param TargetIndex number
---@param OutTangentPoint FVector
---@return boolean
function UParticleSystemComponent:GetBeamTargetTangent(EmitterIndex, TargetIndex, OutTangentPoint) end

---Get the beam target strength false		EmitterIndex or TargetIndex is invalid - OutTargetStrength is invalid
---@param EmitterIndex number
---@param TargetIndex number
---@param OutTargetStrength number
---@return boolean
function UParticleSystemComponent:GetBeamTargetStrength(EmitterIndex, TargetIndex, OutTargetStrength) end

---Enables/Disables a sub-emitter
---@param EmitterName string
---@param bNewEnableState boolean
function UParticleSystemComponent:SetEmitterEnable(EmitterName, bNewEnableState) end

---Change a named float parameter
---@param ParameterName string
---@param Param number
function UParticleSystemComponent:SetFloatParameter(ParameterName, Param) end

---Set a named vector instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param FVector
function UParticleSystemComponent:SetVectorParameter(ParameterName, Param) end

---Set a named color instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param FLinearColor
function UParticleSystemComponent:SetColorParameter(ParameterName, Param) end

---Set a named actor instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param AActor
function UParticleSystemComponent:SetActorParameter(ParameterName, Param) end

---Set a named material instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param UMaterialInterface
function UParticleSystemComponent:SetMaterialParameter(ParameterName, Param) end

---Change the ParticleSystem used by this ParticleSystemComponent
---@param NewTemplate UParticleSystem
function UParticleSystemComponent:SetTemplate(NewTemplate) end

---Get the current number of active particles in this system
---@return number
function UParticleSystemComponent:GetNumActiveParticles() end

---Begins all trail emitters in this component.
---@param InFirstSocketName string
---@param InSecondSocketName string
---@param InWidthMode ETrailWidthMode
---@param InWidth number
function UParticleSystemComponent:BeginTrails(InFirstSocketName, InSecondSocketName, InWidthMode, InWidth) end

---Ends all trail emitters in this component.
function UParticleSystemComponent:EndTrails() end

---Sets the defining data for all trails in this component.
---@param InFirstSocketName string
---@param InSecondSocketName string
---@param InWidthMode ETrailWidthMode
---@param InWidth number
function UParticleSystemComponent:SetTrailSourceData(InFirstSocketName, InSecondSocketName, InWidthMode, InWidth) end

---@param InSocketName string
function UParticleSystemComponent:SetSocketName(InSocketName) end

---@param DeltaTime number
function UParticleSystemComponent:ManuallyTickComponent(DeltaTime) end

---Record a kismet event.
---@param InEventName string
---@param InEmitterTime number
---@param InLocation FVector
---@param InDirection FVector
---@param InVelocity FVector
function UParticleSystemComponent:GenerateParticleEvent(InEventName, InEmitterTime, InLocation, InDirection, InVelocity) end

---Set a named random vector instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param FVector
---@param ParamLow FVector
function UParticleSystemComponent:SetVectorRandParameter(ParameterName, Param, ParamLow) end

---Set a named random float instance parameter on this ParticleSystemComponent. Updates the parameter if it already exists, or creates a new entry if not.
---@param ParameterName string
---@param Param number
---@param ParamLow number
function UParticleSystemComponent:SetFloatRandParameter(ParameterName, Param, ParamLow) end

function UParticleSystemComponent:RewindEmitterInstances() end
