---@meta

---@class FSCSNodeNameChanged : ULuaSingleDelegate
FSCSNodeNameChanged = {}

---绑定回调函数
---@param Callback fun(Obj: any, Param1: string) @回调函数
---@param Obj? any @可选的绑定对象，作为回调第一个参数传入
---@return number @回调引用
function FSCSNodeNameChanged:Bind(Callback, Obj) end

---执行委托
---@param Param1 string
function FSCSNodeNameChanged:Execute(Param1) end


---@class USCS_Node: UObject
---@field CookedComponentInstancingData FBlueprintCookedComponentInstancingData @Cached data for faster runtime instancing (only used in cooked builds)
---@field VariableName string @If non-None, creates a variable in the class and assigns the created blueprint to it
---@field AttachToName string @Socket/Bone that Node might attach to
---@field ParentComponentOrVariableName string @Component template or variable that Node might be parented to
---@field ParentComponentOwnerClassName string @If the node is attached to another node inherited from a parent Blueprint, this contains the name of the Blueprint parent class that owns the component template
---@field bIsParentComponentNative boolean @If the node is parented, this indicates whether or not the template is found in the CDO's Components array
---@field ChildNodes ULuaArrayHelper<USCS_Node> @Set of child nodes
---@field MetaDataArray ULuaArrayHelper<FBPVariableMetaDataEntry> @Metadata information for this Node
---@field VariableGuid FGuid
---@field bIsFalseRoot_DEPRECATED boolean @(DEPRECATED)
---@field bIsNative_DEPRECATED boolean @(DEPRECATED) Indicates if this is a native component or not
---@field NativeComponentName_DEPRECATED string
---@field bVariableNameAutoGenerated_DEPRECATED boolean @(DEPRECATED) If true, the variable name was a autogenerated and is not presented to the user
---@field InternalVariableName string @Internal variable name. This is used for: a) Generating the component template (archetype) object name. b) A UObjectProperty in the generated Blueprint class. This holds a reference to the component instance created at Actor construction time. c) Archetype lookup through the generated Blueprint class. All instances route back to the archetype through the variable name (i.e. not the template name).
local USCS_Node = {}
