---@meta

---@class USynthSound: USoundWaveProcedural
local USynthSound = {}


---@class USynthComponent: USceneComponent
---@field bAutoDestroy number @Auto destroy this component on completion
---@field bStopWhenOwnerDestroyed number @Stop sound when owner is destroyed
---@field bAllowSpatialization number @Is this audio component allowed to be spatialized?
---@field bOverrideAttenuation number @Should the Attenuation Settings asset be used (false) or should the properties set directly on the component be used for attenuation properties
---@field AttenuationOverrides any @If bOverrideSettings is true, the attenuation properties to use for sounds generated by this component
---@field SoundSubmixSends ULuaArrayHelper<FSoundSubmixSendInfo> @An array of submix sends. Audio from this sound will send a portion of its audio to these effects.
---@field bIsUISound number @Whether or not this sound plays when the game is paused in the UI
local USynthComponent = {}

function USynthComponent:Start() end

function USynthComponent:Stop() end

---Returns true if this component is currently playing.
---@return boolean
function USynthComponent:IsPlaying() end

---Sets how much audio the sound should send to the given submix.
---@param Submix USoundSubmix
---@param SendLevel number
function USynthComponent:SetSubmixSend(Submix, SendLevel) end
