---@class Ingame_Photo_UIBP_C:UPhotoUI
---@field UIMsg_QuitPhoto:fun()
---@field UIMSG_SetPhotoUICreatedBy:fun(CreatedBy:FString)
---@field InitExpressionUI:fun(ExpressionUI:QuickExpressionUIBP_C)
---@field FindExpressionUI:fun():UCanvasPanel,QuickExpressionUIBP_C
---@field SetPawnVisible:fun(SelfHidden:bool,TeammateHidden:bool,EnemyHidden:bool)
---@field SetCameraModeUI:fun(NewCameraMode:EFutureTechCameraMode)
---@field Tips2_anima UWidgetAnimation
---@field Tips1_anima UWidgetAnimation
---@field Border_Ingame_PhotoTips1 UBorder
---@field Border_Ingame_PhotoTips2 UBorder
---@field CanvasPanel_1 UCanvasPanel
---@field CanvasPanel_Ingame_Emote UCanvasPanel
---@field CanvasPanel_Ingame_Photo1 UCanvasPanel
---@field CanvasPanel_Ingame_PhotoClose UCanvasPanel
---@field CanvasPanel_Mode_Set_Content UCanvasPanel
---@field CanvasPanel_Photo2 UCanvasPanel
---@field CanvasPanel_ShareLayer UCanvasPanel
---@field HideSelf UNewCheckBox
---@field HideTeammates UNewCheckBox
---@field Image_BtnIcon UImage
---@field Image_IngameLogo UImage
---@field InvalidationBox_3 UInvalidationBox
---@field InvalidationBox_6 UCanvasPanel
---@field InvalidationBox_8 UCanvasPanel
---@field NewButton_CloseUI UNewButton
---@field NewButton_Ingame_ModeClose UNewButton
---@field NewButton_Ingame_ModeSet UNewButton
---@field NewButton_Ingame_Photo1 UNewButton
---@field NewButton_Ingame_PhotoOut UNewButton
---@field NewButton_Photo2 UNewButton
---@field WidgetSwitcher_IconType UWidgetSwitcher
---@field Run6 UWidget
---@field Run8 UWidget
---@field Run7 UWidget
---@field ShareUI Ingame_Photo_Share_UIBP_C
---@field CreateBy Ingame_Photo_CreateMode
