---@class Superman_Machete_3_C:ASTExtraWeapon
---@field GetSkillIndexForMeleeWeapon:fun():int32
---@field GetSkillEntryForMeleeWeapon:fun(IsPressed:bool):EUTSkillEntry
---@field UserConstructionScript:fun()
---@field Box UBoxComponent
---@field WeaponTriggerEventHandleSkill UWeaponTriggerEventHandleSkill
---@field CrossHair UCrossHairComponent
---@field WeaponStateDefault UWeaponStateDefault
---@field WeaponStateManager UWeaponStateManager
---@field WeaponSpecificHandler UWeaponSpecificHandler
---@field WeaponAnimList_Melee WeaponAnimList_Melee_C
---@field WeaponEntity UWeaponEntity
