---@class CustomUIPositionInterface_C:UInterface
---@field IsCustomUIDataValid:fun(Widget:UWidget,SaveDataSize:FVector2D):bool
---@field SetSettingControlUI:fun()
---@field SetCustomizeUIInfo:fun(SaveGame:BP_SAVEGAME_UIElemLayout_C,FireMode:int32)
