---@class ECurPlayerHandStatus
---@field NewEnumerator0 int32
---@field NewEnumerator1 int32
---@field NewEnumerator2 int32
---@field NewEnumerator3 int32
---@field NewEnumerator4 int32
---@field ECurPlayerHandStatus_MAX int32
